name: Ippex BuildTool
description: Executes the Ippex Build Tool.

inputs:
  checkout:
    description: Boolean flag which declares if git checkout should take place or not by this script.
    required: true
    default: 'true'
  installRequired:
    description: Boolean flag which declares if should install required tools.
    required: true
    default: 'true'
  target:
    description: The command to run.
    required: false
    default: Default

runs:
  using: composite
  steps:
   
    - if: ${{ inputs.checkout == 'true' }} 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - if: ${{ inputs.installRequired == 'true' }}
      shell: bash
      run: |
        dotnet nuget locals http-cache --clear
        dotnet tool update -g BuildTool
        
    - run: echo "::add-matcher::${GITHUB_ACTION_PATH}/matcher.json"
      shell: bash
      
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.target }}
      shell: bash
      
    - run: echo "::remove-matcher owner=bash-action::"
      shell: bash
